#!/usr/bin/env bash
# Install user-supplied static assets. No UI assets are generated by this project stage.
set -Eeuo pipefail
SOURCE=${1:-}
[[ $# == 1 && -d $SOURCE && -f $SOURCE/index.html && ! -L $SOURCE ]] || {
    echo 'sudo satdump-station ui-deploy DIRECTORY (в каталоге нужен index.html)' >&2; exit 2;
}
(( EUID == 0 )) || { echo 'Нужен sudo' >&2; exit 1; }
[[ -z $(find "$SOURCE" -type l -print -quit) ]] || { echo 'Символьные ссылки в интерфейсе запрещены' >&2; exit 1; }
PREFIX=/opt/satdump-station/board-ui
install -d -m 0755 "$PREFIX/releases" /run/lock
exec 9>/run/lock/satdump-ui-deploy.lock
flock -n 9 || { echo 'Развёртывание интерфейса уже работает' >&2; exit 1; }
STAGE=$(mktemp -d "$PREFIX/releases/.stage.XXXXXXXX")
trap '[[ -z ${STAGE:-} ]] || rm -rf -- "$STAGE"' EXIT
cp -a "$SOURCE/." "$STAGE/"
[[ -z $(find "$STAGE" -type l -print -quit) ]] || { echo 'В источнике появилась ссылка' >&2; exit 1; }
# Reject device files, FIFOs and sockets even for a trusted administrator's directory.
[[ -z $(find "$STAGE" ! -type f ! -type d -print -quit) ]] || { echo 'Допускаются только обычные файлы' >&2; exit 1; }
chown -R root:root "$STAGE"
find "$STAGE" -type d -exec chmod 0755 '{}' +
find "$STAGE" -type f -exec chmod 0644 '{}' +
VERSION=$(date -u +%Y%m%dT%H%M%SZ)-$$
TARGET="$PREFIX/releases/$VERSION"
mv "$STAGE" "$TARGET"; STAGE=''
if [[ -L $PREFIX/current ]]; then ln -sfn "$(readlink -f "$PREFIX/current")" "$PREFIX/previous"; fi
ln -sfn "$TARGET" "$PREFIX/.next"
mv -Tf "$PREFIX/.next" "$PREFIX/current"
printf 'Интерфейс подключён: %s. Перезапуск WEB не требуется.\n' "$VERSION"
